version: "3"
services:
  spring-boot:
    build: 
      context: ./twitter-kafka
    environment: 
      - TWITTER_API_KEY
      - TWITTER_API_SECRET_KEY
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET