twitter:
  api_key: ${TWITTER_API_KEY}
  api_secret_key: ${TWITTER_API_SECRET_KEY}
  access_token: ${TWITTER_ACCESS_TOKEN}
  access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}
  max_messages: 100
  client_name: "Twitter-Client"
  terms: kafka,springboot,quarkus,microservices
  debug: true
kafka:
  boostrap_servers: "127.0.0.1:9092"
  topic: "tweets"
  debug: true
elasticsearch:
  hostname: ${ES_HOSTNAME}
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  index: "twitter"
  type: "tweets"
  debug: true
